#!/bin/bash

# variable for base directory
BaseDir=$(pwd)
DBCount=$(ls -d */ | wc -l)
# variable for exit message
shopt -s extglob
mainMenu="1)Create database 2)List databases 3)Connect to database 4)Drop database 5)Exit"
function main {
  # start menu
  echo "Welcome to ITI DBMS"
  echo "Working directory: $BaseDir"
  echo "This directory contains $DBCount databases"
  echo "=========================="

  select option1 in "Create database" "List databases" "Connect to database" "Drop database" "Exit"; do
    if [ $(pwd) != $BaseDir ]; then
      cd ${BaseDir}
      echo "returned to base directory: $BaseDir"
    fi
    case $option1 in
    "Create database")
      createDB
      dbMenu
      ;;
    "List databases")
      checkDB
      flag=$?
      if [ $flag -eq 0 ]; then 
        listDB
      fi
      dbMenu
      ;;
    "Connect to database")
      checkDB
      flag=$?
      if [ $flag -eq 0 ]; then
        connectDB
      fi
      dbMenu
      ;;
    "Drop database")
      checkDB
      flag=$?
      if [ $flag -eq 0 ]; then
        dropDB
      fi
      dbMenu
      ;;
    "Exit")
      break
      ;;
    *)
      echo "Invalid option. Please try again."
      dbMenu
      ;;
    esac
  done
}


function createDB() {
  while true
  do
    read -p "Please enter your DB name: " DBName
    if [[ 'exit' =~ $DBName ]] ; then
      echo "Exiting..."
      break
    fi
    # check if name starts with letter and replace spaces with _
    if [[ ${DBName:0:1} =~ [a-zA-Z] ]] && [[ $DBName =~ ^[a-zA-Z0-9[:space:]]*$ ]] ; then
      DBName=${DBName// /_}
    else
      echo "Name should start with a letter and has no special characters"
      continue
    fi
    if [ -d "./$DBName" ] ; then
      echo "$DBName already exists"
      continue
    fi
    mkdir "$DBName"
    echo "Successfully created $DBName"
    break
  done
}

# list databases
function listDB() {
  echo "Databases list:"
  echo "=========================="
  # multi line
  ls -d */ | sed 's/[/]/ /g'
  echo "=========================="
}

# connect to database by cd to its directory
function connectDB() {
  getDB
  echo "Please enter the number of the database you want: "
  select option2 in "${databases[@]}" "Exit"; do
    case $option2 in
    "Exit")
      echo "Exiting..."
      break
      ;;
    *)
      DBConnect=$option2
      if [[ -d "$DBConnect" ]]; then
        cd "$DBConnect"
        accessTables "$DBConnect"
        # after exit accessTables (disconnect)
        cd ..
        echo "Disconnected from DB $DBConnect"
        break
      else
        # $REPLY is the selected number
        echo "Database with number $REPLY does not exist."
        echo "Please enter valid number for the database you want: "
      fi
      ;;
    esac
  done
}

# drop database
function dropDB() {
  getDB
  echo "Please enter the number of the database you want to drop: "
  select option2 in "${databases[@]}" "Exit to main menu"; do
    case $option2 in
    "Exit to main menu")
      echo "Exiting..."
      break
      ;;
    *)
      DBDrop=$option2
      if [[ -d "$DBDrop" ]]; then
        read -p "Are you sure you want to permanently drop $DBDrop? [y/n]: " dropFlag
        if [[ "yes" =~ "$dropFlag" ]]; then
          rm -r "$DBDrop"
          echo "$DBDrop is successfully dropped"
          break
        else
          echo "Database drop cancelled."
          break
        fi
      else
        echo "Database with number $REPLY does not exist."
        echo "Please enter valid number for the database you want to drop: "
      fi
      ;;
    esac
  done
}


# Check if any DB exists
function checkDB() {
  if [ $(ls -d */ 2> /tmp/err | wc -w) -eq 0 ]; then
    echo "No databases found."
    return 1
  fi
}

function getDB() {
  databases=($(ls -d */ | sed 's/[/]//g'))
  return
}

function dbMenu(){
  db="Current Directory: $BaseDir,\n1)Create database\n2)List databases\n3)Connect to database\n4)Drop database\n5)Exit"
  echo -e $db
}

# ===========================
# Table functions
# ===========================
# need to implement createTable, insertTable, selectTable, removeTable.
# drop and list is done


function accessTables() {
  echo "Welcome to $1 database in $(pwd)"
  tables=$(ls -p | grep -v / | grep -v "^\.")
  if [[ -n ${tables[@]} ]]; then
    select option3 in "Create table" "List tables" "Drop Table" "Insert into Table" "Select From Table" "Delete From Table" "Exit"; do
    case $option3 in
    "Create table")
      createTable
      tableMenu $1
      ;;
    "List tables")
      listTables
      tableMenu $1
      ;;
    "Drop Table")
      dropTable
      tableMenu $1
      ;;
    "Insert into Table")
      insertTable
      tableMenu $1
      ;;
    "Select From Table")
      selectTable
      tableMenu $1
      ;;
    "Delete From Table")
      deleteFromTable
      tableMenu $1
      ;;
    "Exit")
      break
      ;;
    *)
      echo "Invalid entry. Please try again."
      ;;
    esac
  done 
  else
    echo "To access the full menu please create a table"
    select option3 in "Create table" "Exit"; do
    case $option3 in
    "Create table")
      createTable
      echo $menu
      ;;
    "Exit")
      break
      ;;
    *)
      echo "Invalid entry. Please try again."
      ;;
    esac
  done
  fi
}

# implement (int, str, primary key) in metadata file, and tablename validation
function createTable() {
  while true
    do
  read -p "Please enter new table's name or type exit: " tableName
    case $tableName in
    @([eE][xX][iI][tT]))
      echo "exiting.."
      return
      ;;
    +([a-zA-Z])*([a-zA-Z0-9|" "]))
      tableName=${tableName/" "/"_"}
      echo "$tableName is a valid name"
      break
      ;;
    *)
      echo "Name should start with only letters and can't have any special characters."
      ;;
    esac
  done
  if [ -e "./$tableName" ]; then
    echo "Table $tableName already exists"
    return
  else
    while true
      do
        read -p "Enter the number of columns in the table: " colNum
        if [[ $colNum =~ ^[0-9]+$ && $colNum -gt 0 ]]; then
          break
        else
          echo "Error: Number of columns must be a positive integer"
        fi
      done
    for ((i=0;i<$colNum;i++))
    do
      line=""

      if [[ $i -eq 0 ]]
      then
        while true
        do
          read -p "Please enter the name of you primary key column " colName
          case $colName in
          +([a-zA-Z])*([a-zA-Z0-9|" "]))
            colName=${colName/" "/"_"}
            line+=$colName
            break
            ;;
          *)
            echo "column Name should start with only letters and can't have any special characters."
            ;;
          esac
        done

        while true
        do
          read -p "Please enter the primary key column type (int/str): " colType
          case $colType in
          "int")
            line+=:$colType
            break
            ;;

          "str")
            line+=:$colType
            break
            ;;
          *)
            echo "Invalid entry, please enter (int/str)."
            ;;
          esac
        done
        line+=:pk

      else
        while true
          do
            read -p "Please enter the name of the column: " colName
            case $colName in
            +([a-zA-Z])*([a-zA-Z0-9|" "]))
              colName=${colName/" "/"_"}
              line+=$colName
              break
              ;;
            *)
              echo "column Name should start with only letters and can't have any special characters. "
              ;;
            esac
          done

        while true
          do
            read -p "Please enter column type (int/str): " colType
            case $colType in
            "int")
              line+=:$colType
              break
              ;;

            "str")
              line+=:$colType
              break
              ;;
            *)
              echo "Invalid entry, please enter (int/str). "
              ;;
            esac
        done

      fi
    echo $line >> .$tableName"_metadata"

    done

    
    # implement (int, str, primary key) in metadata file, and tablename validation
    touch "$tableName"
    echo "Table $tableName is successfully created"
    echo "================================================================================"
  fi
}

function listTables() {
  echo "Tables list:"
  echo "=========================="
  ls -p | grep -v / | grep -v "^\."
}


# implement insert logic
# pseudocode:
# 1) ask user to enter name of table he want to insert to.
# 2) perform name validation.
# 3)get the pk column from metadata.

function insertTable() {
  tables=$(ls -p | grep -v / | grep -v "^\.")
  echo "Here are the tables in this database: "
  echo "================================================================================"
  echo $tables
  echo "================================================================================"
  while true
  do
    read -p "Please enter the name of the table you want to insert into: " choice
    case $choice in
    #to verify first character to be a letter and to accept letters , numbers and underscore.
      +([a-zA-Z])*([a-zA-Z0-9|"_"]))
        tableName=$choice
        if [ -f "./$tableName" ]
        then
          types=$(awk -F : ' {print $2} ' ./"."$tableName"_metadata" )
          names=$(awk -F : ' {print $1} ' ./"."$tableName"_metadata" )
          #to change string to an array. ==> hello my friend --> [hello,my,friend]
          namesArray=($names)
          typesArray=($types)
          # echo ${namesArray[@]}
          # echo ${typesArray[@]}
          numberOfColumns=$(awk -F : ' {} END {print NR}' ./"."$tableName"_metadata" )
          echo "We have $numberOfColumns columns in table: $tableName "
          
          newTableLine=""
          for (( i=0;i<numberOfColumns;i++ ))
          do
            if [[ "${typesArray[$i]}" == "int" ]]
            then
              while true
              do
                duplicateFlag=false
                read -p "Enter the ${typesArray[$i]} value for column ${namesArray[$i]}: " columnInput
                if [[ $columnInput =~ ^[0-9]+$ && $columnInput -ge 0 ]];
                then
                  previousIds=$(awk -F : ' {print $1} ' ./$tableName )
                  if [[ $i -eq 0 ]]
                  then
                    for previous in $previousIds
                    do
                      if [[ "$previous" == "$columnInput" ]]
                      then
                        echo "Error: $columnInput already exists, Please type try another id "
                        duplicateFlag="true"
                        break
                      fi
                    done
                    if [[ "$duplicateFlag" == "false" ]]
                    then
                      newTableLine+=$columnInput
                      break
                      continue
                    fi
                  else
                  newTableLine+=":$columnInput"
                  fi
                  
                  if [[ "$duplicateFlag" == "true" ]]
                  then
                    continue
                  else
                    break

                    continue
                  fi
                  
                else
                  echo "Error ${namesArray[$i]} should be integer number "
                fi
              done
            #to handle if the column is a string.
            else
              while true
              do
                duplicateFlag=false
                read -p "Enter the ${typesArray[$i]} value for column ${namesArray[$i]}: " columnInput
                  #change all string primary keys to lowercase before handling duplication
                  columnInput=$(echo "$columnInput"| awk '{print tolower($0)}')
                  previousIds=$(awk -F : ' {print $1} ' ./$tableName )
                  if [[ $i -eq 0 ]]
                  then
                    for previous in $previousIds
                    do
                      if [[ "$previous" == "$columnInput" ]]
                      then
                        echo "Error: $columnInput already exists, Please type try another id "
                        duplicateFlag="true"
                        break
                      fi
                    done
                    if [[ "$duplicateFlag" == "false" ]]
                    then
                      newTableLine+=$columnInput
                      break
                      continue
                    fi
                  else
                    newTableLine+=":$columnInput"
                  fi
                  
                  if [[ "$duplicateFlag" == "true" ]]
                  then
                    continue
                  else
                    break

                    continue
                  fi
              done
              
              continue

            fi


            

          done
          echo $newTableLine >> ./$tableName


          echo "Data inserted successfully"
          echo "================================================================================"
          break
        else
          echo "Error: Table doesn't exist, please try again. "
        fi
        ;;
      *)
        echo "Error, table name must start with a letter and doesn't have any special characters, Please try again "
    esac
  done
  return
}

function selectTable() {
  tables=($(ls -p | grep -v / | grep -v "^\."))
  echo "Please enter the name or number of the table you want: "
  select searchTable in "${tables[@]}" "Exit"; do
    case $searchTable in
    "Exit")
      echo "Exiting..."
      break
      ;;
    *)
      if [ -f "./$searchTable" ]; then
        echo "Select condition:"
        select selectCondition in "All" "By Column" "Projection" "Exit"; do
          case $selectCondition in
          "All")
            echo "All data in $searchTable: " && cat ./"$searchTable" && echo ""
            break 2
            ;;
          "By Column")
              columns=($(awk -F ":" '{print $1}' "./.$searchTable"_metadata))
              
                echo "Please enter the name of the column you want: "
                select choice in "${columns[@]}" "Exit"; do
                case $choice in
                "Exit")
                  echo "Exiting..."
                  break 3
                  ;;
                *)
                if [[ $REPLY -le ${#columns[@]} && ${#columns[@]} -gt 0 && $REPLY -gt 0 ]] then
                  read -p "Please enter the value of $choice: " value
                  found=$(awk -F ":" -v reply="$REPLY" -v value="$value" '$reply == value {print $0}' "./$searchTable")
                  if [ -n "$found" ]; then
                    echo "Here is all records with column $choice = $value in $searchTable"
                    echo "============="
                    echo "$found"
                    echo "============="
                    break 3
                  else
                    echo "No records found with column $choice = $value"
                    echo "Select another column number or $((${#columns[@]} + 1)) to exit"
                  fi
                else
                  echo "Invalid column name."
                fi
                  ;;
                esac
              done
              break
            ;;
          "Projection")
            columns=($(awk -F ":" '{print $1}' "./.$searchTable"_metadata))
                echo "Please enter the name of the column you want to project: "
                select choice in "${columns[@]}" "Exit"; do
                  case $choice in 
                    "Exit")
                      echo "Exiting..."
                      break 3
                      ;;
                    *)
                      if [[ $REPLY -le ${#columns[@]} && ${#columns[@]} -gt 0 && $REPLY -gt 0 ]] then
                        projection=$(awk -F ":" -v reply="$REPLY" '{print $reply "\n"}' "./$searchTable")
                        echo "Projection for column $choice in table $searchTable: "
                        echo "$projection"
                        break 3
                      else
                        echo "wrong column name"
                      fi
                      ;;
                esac
                done
            ;;
          "Exit")
            echo "Exiting..."
            break
            ;;
          esac
        done
      else
        echo "Table with number $REPLY does not exist."
      fi
      ;;
    esac
  done
}

function deleteFromTable() {
  # implement remove logic
  tables=$(ls -p | grep -v / | grep -v "^\.")
  echo "Here are the tables in this database: "
  echo "================================================================================"
  echo $tables
  echo "================================================================================"
  while true ;do #outer while
    read -p "Please enter the name of the table you want to Delete From: " choice
    case $choice in
      +([a-zA-Z])*([a-zA-Z0-9|"_"]))
        tableName=$choice
        if [ -f "./$tableName" ];then
          echo "Table exists"
          select choice2 in "By id" "By Column" "Exit"; do
            case $choice2 in #second
              "By id")
                pktype=$(awk -F : ' {if(NR==1){print $2}} ' ./"."$tableName"_metadata" )
                pkName=$(awk -F : ' {if(NR==1){print $1}} ' ./"."$tableName"_metadata" )

                if [[ "$pktype" == "int"  ]];then
                  while true ;do #third
                    idExistFlag=false
                    read -p "Please Enter $pkName of the row you want to delete (Only Numbers are accepted): " pkInput
                    if [[ $pkInput =~ ^[0-9]+$ && $pkInput -ge 0 ]]; then
                      #check if the entered PK exists or not
                      previousIds=$(awk -F : ' {print $1} ' ./$tableName )
                      #change string to array
                      previousIdsArray=($previousIds)
                      previousIdsCount=$(awk -F : ' END {print NR}' ./$tableName )
                      pkInputIndex=0
                      for (( i=0;i<previousIdsCount;i++ ));do #fourth
                        if [[ "${previousIdsArray[$i]}" == "$pkInput" ]];then
                          idExistFlag=true
                          ((pkInputIndex=$i+1))
                          break #from fourth
                        fi
                      done
                      if [[ "$idExistFlag" == "true" ]];then
                        echo "$pkName is found sucessfully"
                        sed -i "${pkInputIndex}d" ./$tableName
                        echo "Row is deleted successfully"
                        break #from third
                      else
                        echo "this $pkName is not found please try again."
                      fi
                      
                      
                    else
                      echo "Error: Number must be a positive integer"
                    fi
                  done
                else
                  echo "Hello from str"
                fi
                break #from second
                ;;
              "By Column")
                types=$(awk -F : ' {print $2} ' ./"."$tableName"_metadata" )
                names=$(awk -F : ' {print $1} ' ./"."$tableName"_metadata" )
                values=$(awk -F : ' {print $1} ' ./"."$tableName"_metadata" )
                namesArray=($names)
                typesArray=($types)
                select option5 in "${namesArray[@]}";do #five
                  case $REPLY in
                    [1-9]*)
                      if (( $REPLY >= 1 && $REPLY <= ${#namesArray[@]} )); then # #is used to get the length of the array
                        
                        echo "you selected: $option5"
                        
                        break #from five
                      else
                        echo "Invalid selection. Please try again"
                      fi

                      ;;
                    *)
                      echo "please enter a valid number"
                  
                  esac
                done
                break #from second
                ;;
              "Exit")
                echo "Exiting..."
                break #from second case
                ;;
              *)
                echo "Please enter a valid number from the menu"
            esac
          done
          break #for the outer While true
        else
          echo "Error: Table doesn't exist, please try again. "
        fi
        ;;
      *)
        echo "Error, table name must start with a letter and doesn't have any special characters, Please try again "
    esac
  done
}


# drop table
function dropTable() {
  tables=$(ls -p | grep -v / | grep -v "^\.")
  select TBdrop in "$tables" "Exit"; do
    case $TBdrop in
    "Exit")
      echo "Exiting..."
      break
      ;;
    *)
      if [ -f "./$TBdrop" ]; then
        read -p "Are you sure you want to permanently drop $TBdrop? [y/n]: " dropFlag
        if [[ "$dropFlag" == "y" ]]; then
          rm "$TBdrop"
          echo "$TBdrop is successfully dropped"
          break
        else
          echo "Table drop operation cancelled."
          break
        fi
      else
        echo "Table $TBdrop does not exist."
      fi
      ;;
    esac
  done
}
function tableMenu(){
  tableMenu="Current DB: $1,\n1) Create table,\n2) List tables,\n3) Drop Table,\n4) Insert into Table,\n5) Select From Table,\n6) Delete From Table,\n7) Exit"
  echo -e $tableMenu
}

main